import { Shipment, InventoryItem, Warehouse, ReportItem } from './types';

export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    id: 'LI-7700-4829-XQ',
    carrier: 'OCEAN-BRIDGE LOGISTICS',
    vesselId: 'OB-X992-G',
    origin: 'Port of Shanghai, CN',
    destination: 'Singapore Port, SG',
    status: 'In Transit',
    eta: 'OCT 24, 2026',
    weight: '14,240.50 KG',
    mode: 'Sea',
    vesselName: 'MARITIME STAR VII',
    cruisingSpeed: '18.4 KNOTS',
    temperature: '4°C',
    waypoints: [
      {
        id: 'wp1',
        time: 'Oct 18 • 09:45',
        title: 'Origin Departure',
        description: 'Port of Shanghai, Terminal 4',
        status: 'completed',
      },
      {
        id: 'wp2',
        time: 'Oct 19 • 14:20',
        title: 'International Waters',
        description: 'Vessel crossing East China Sea',
        status: 'completed',
      },
      {
        id: 'wp3',
        time: 'In Transit',
        title: 'Approaching Port',
        description: 'Estimated proximity 450nm',
        status: 'active',
      },
      {
        id: 'wp4',
        time: 'Estimated Oct 24',
        title: 'Customs Clearance',
        description: 'Singapore Central Port Customs Area',
        status: 'pending',
      },
      {
        id: 'wp5',
        time: 'Estimated Oct 25',
        title: 'Final Delivery',
        description: 'Warehouse Central Complex',
        status: 'pending',
      },
    ],
  },
  {
    id: 'SHP-99281-XM',
    carrier: 'Maersk Line',
    vesselId: 'MR-K381-H',
    origin: 'Shenzhen, CN',
    destination: 'Rotterdam, NL',
    status: 'In Transit',
    eta: 'Oct 24, 2026',
    weight: '22,480.00 KG',
    mode: 'Sea',
    vesselName: 'MAERSK VANGUARD',
    cruisingSpeed: '21.0 KNOTS',
    temperature: 'Ambient',
    waypoints: [
      {
        id: 'wp1',
        time: 'Oct 12 • 06:00',
        title: 'Cargo Received',
        description: 'Shenzhen Port Terminal',
        status: 'completed',
      },
      {
        id: 'wp2',
        time: 'Oct 14 • 11:30',
        title: 'Maritime Departure',
        description: 'Departed main terminal, routing west',
        status: 'completed',
      },
      {
        id: 'wp3',
        time: 'Oct 20 • 23:15',
        title: 'Indian Ocean Transit',
        description: 'Routing around Horn of Africa due to Suez advisory',
        status: 'active',
      },
      {
        id: 'wp4',
        time: 'Estimated Oct 24',
        title: 'Customs Clearance Rotterdam',
        description: 'Awaiting container scanning',
        status: 'pending',
      },
    ],
  },
  {
    id: 'AIR-4420-LAX',
    carrier: 'MSC Logistics',
    vesselId: 'MSC-LAX-4420',
    origin: 'Frankfurt, DE',
    destination: 'Los Angeles, US',
    status: 'Processing',
    eta: 'Oct 22, 2026',
    weight: '4,500.00 KG',
    mode: 'Air',
    vesselName: 'BOEING 747-8F',
    cruisingSpeed: '490 KNOTS',
    temperature: '18°C',
    delayDetail: 'None',
    waypoints: [
      {
        id: 'wp1',
        time: 'Oct 19 • 10:00',
        title: 'Manifest Cleared',
        description: 'Frankfurt Cargo City South',
        status: 'completed',
      },
      {
        id: 'wp2',
        time: 'Oct 20 • 18:45',
        title: 'Security Control Approval',
        description: 'Sterile cargo area certified',
        status: 'completed',
      },
      {
        id: 'wp3',
        time: 'Oct 21 • 04:30',
        title: 'Loading Phase',
        description: 'Positioning on Main Deck Pallet Slot A4',
        status: 'active',
      },
    ],
  },
  {
    id: 'TRK-8812-ORD',
    carrier: 'Hapag-Lloyd Express',
    vesselId: 'TRK-ORD-8812',
    origin: 'Chicago, US',
    destination: 'Milwaukee, US',
    status: 'Exception',
    eta: 'Oct 21, 2026',
    weight: '8,000.00 KG',
    mode: 'Road',
    vesselName: 'Freightliner Cascadia',
    cruisingSpeed: '55 MPH',
    temperature: 'Ambient',
    delayDetail: 'Delayed: Port Congestion / Highway Construction',
    waypoints: [
      {
        id: 'wp1',
        time: 'Oct 19 • 08:30',
        title: 'Origin Terminal Pickup',
        description: 'Chicago Intermodal Yard',
        status: 'completed',
      },
      {
        id: 'wp2',
        time: 'Oct 19 • 14:00',
        title: 'Route Hold Notice',
        description: 'Road closure on Interstate 94 Northward',
        status: 'completed',
      },
      {
        id: 'wp3',
        time: 'Oct 20 • 09:00',
        title: 'Detour In Effect',
        description: 'Delayed at local state weight checkpoint',
        status: 'active',
      },
    ],
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    sku: 'OPT-992-CN',
    name: 'Ultra-Vision Lens System',
    warehouse: 'Singapore Central',
    stockLevel: 1240,
    status: 'In Stock',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCKuMXPhw_DWahqmJmvfPf3KsSMMGd3QpIGNmdDXUiHTjh3rtY5dMlunjGODVZi9QzL9TiJ4-gEOb2XCQI5OeHMiYkgitGl6YxtS6ixAPIWGz9iWrBpiD3oduUTLRtXZ5ahfwRiHF65LO2dANNEOs584huyKw0iJpYJ9VeGpM1HWxa69U15PcwAOo05ZPb5jmZXWrVmRW1DCv5deZhoueWeOTN3CuCqmwUAgNKzzXd-yOdRlKrDhpaoesdIjQIIxIltAPtjZlNmubI',
    category: 'Optical',
  },
  {
    sku: 'CHIP-441-LA',
    name: 'X-104 Semiconductor Core',
    warehouse: 'Los Angeles West',
    stockLevel: 12,
    status: 'Low Stock',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBz9SZ-POTceKiQywr7rxm0aBClqgjuC0bglYUCabDnnqr9BFgQeLE8-RrM0Kwd94dvBbPjJ_bAPGMpL3HLfV381CxG4Nf4SEyJ4WogSrg8C7tbyKGDKpX2ylNWj0IsxaRe4K5O-xolTkzZtBwpybeh5YPnRIDt5JSqwoYqf8XTwexxrr5_P9Ib--sZgAhgJzP7Qi2R7aB6UXgRpEbB1-M14vy6msIKuGZi6rXupkvFQzLzG_7WORkNEKZfKjL3OULlpJvrvTkOv7g',
    category: 'Semiconductor',
  },
  {
    sku: 'MEC-003-RT',
    name: 'Hydraulic Valve Assembly',
    warehouse: 'Rotterdam Port',
    stockLevel: 0,
    status: 'Out of Stock',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCwUtGc1jboPAACdYryRgrdWlqmQ80_C3eHwARW9_GYriCKsPhaTyp5fyy01AJRQkQJe9cC9YxnoRyaYtwBzGZ6sdhG40BT8lE1J3TzyUfzjZbNdAUmSyhAvLrSXK3HxQ_RmLh9ovza6tGvzpGjBI3xIrgjUu9U9mmaiYg-RCS3AG1UV0FqS9rlCxhuD1h--ac3KI6MGYnXT7AEgqWBV1VnMkEKaRgDTJYCJEu1InLjBgXMqFQA54VPrt0jyvQ5OxZkWPMhOgRiGtw',
    category: 'Mechanical',
  },
  {
    sku: 'MED-550-DB',
    name: 'Medical Cooling Unit P-2',
    warehouse: 'Dubai Logistics City',
    stockLevel: 482,
    status: 'In Stock',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA9_ZqhcpZHbCGwXLPTDYgxjq5eX6U5jmyqYH3gbrL5kAokPTzWicJSWt2TLcKzQiq0sc_a_oHbzNnTgjKveaMIfcC57sGgmWzGtGIr5l53aE-Zk9K-6h8spqaw5mv98TX_VP4cwsJt6KMA9WYxyN0n9d0oNpPPKL0QzkkcZsgNlH97B0_wfO1m7K3iSycFfMiEW3lAIZawKiv9IdwuEKspwXjDJuF6Ol2s3O12wCvVlqNAIR5zLWjy9Y5D-QLr1ZgsrsOABGscSMg',
    category: 'Medical',
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    name: 'Singapore Central',
    used: 82,
    status: 'Optimal',
    icon: 'hub',
  },
  {
    name: 'Rotterdam Port',
    used: 94,
    status: 'Near Capacity',
    icon: 'anchor',
  },
  {
    name: 'Los Angeles West',
    used: 67,
    status: 'Optimal',
    icon: 'warehouse',
  },
  {
    name: 'Dubai Logistics City',
    used: 41,
    status: 'Optimal',
    icon: 'flight_land',
  },
];

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'rep-q3',
    name: 'Q3 Performance Audit',
    type: 'PDF',
    size: '4.2 MB',
    date: 'Oct 12, 2026',
    icon: 'description',
  },
  {
    id: 'rep-opt',
    name: 'Cost Optimization Data',
    type: 'XLSX',
    size: '12.8 MB',
    date: 'Oct 10, 2026',
    icon: 'table_view',
  },
  {
    id: 'rep-delay',
    name: 'Transit Delay Analysis',
    type: 'PDF',
    size: '1.1 MB',
    date: 'Oct 05, 2026',
    icon: 'analytics',
  },
];
